// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq6q4ZDsonA0RQ31eK22faTeX1NiZlWdI',
    appId: '1:853755032440:web:e4024d7ca1222daac14e8d',
    messagingSenderId: '853755032440',
    projectId: 'school-companion-project',
    authDomain: 'school-companion-project.firebaseapp.com',
    storageBucket: 'school-companion-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU8G2J5iFPo9o-dajMGgiP4RTg-e7va7A',
    appId: '1:853755032440:android:1c8cd93ea12f4cbec14e8d',
    messagingSenderId: '853755032440',
    projectId: 'school-companion-project',
    storageBucket: 'school-companion-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu06SdaimMQSff-GaOCjYG674evKqSVWQ',
    appId: '1:853755032440:ios:f68f128ff3e54885c14e8d',
    messagingSenderId: '853755032440',
    projectId: 'school-companion-project',
    storageBucket: 'school-companion-project.firebasestorage.app',
    iosBundleId: 'com.hendrick.schoolCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu06SdaimMQSff-GaOCjYG674evKqSVWQ',
    appId: '1:853755032440:ios:f68f128ff3e54885c14e8d',
    messagingSenderId: '853755032440',
    projectId: 'school-companion-project',
    storageBucket: 'school-companion-project.firebasestorage.app',
    iosBundleId: 'com.hendrick.schoolCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq6q4ZDsonA0RQ31eK22faTeX1NiZlWdI',
    appId: '1:853755032440:web:908860557b4507f9c14e8d',
    messagingSenderId: '853755032440',
    projectId: 'school-companion-project',
    authDomain: 'school-companion-project.firebaseapp.com',
    storageBucket: 'school-companion-project.firebasestorage.app',
  );
}
